// Shared constants for prayer request exports

export const CALENDAR_DATA: Record<number, { name: string; events: string[] }> = {
  0: {
    name: "January",
    events: [
      "4-11 Grace Gift Emphasis",
      "7 Prayer Vigil",
      "11 Senior Citizen Sunday",
      "18 Ministry Clinic",
      "31 Dawn Prayer Breakfast",
    ],
  },
  1: {
    name: "February",
    events: ["15 Couple's Sunday", "28 Dawn Prayer Breakfast"],
  },
  2: {
    name: "March",
    events: [
      "1-29 Mission Emphasis",
      "25 Prayer Vigil",
      "28 Dawn Prayer Breakfast",
      "29 Faith Promise Commitment",
    ],
  },
  3: {
    name: "April",
    events: [
      "1-3 NEGROS YOUTH CAMP",
      "5 Pastor & Ma'am Bel Wedding Anniversary",
      "10 Good Friday",
      "11 Children's Rally",
      "19-26 First Fruit Emphasis",
      "25 Dawn Prayer Breakfast",
    ],
  },
  4: {
    name: "May",
    events: ["10 Mother's Sunday", "27 Prayer Vigil", "30 Dawn Prayer Breakfast"],
  },
  5: {
    name: "June",
    events: [
      "7 42ND CHURCH ANNIVERSARY",
      "21 Father's Sunday | Host: Bro. Aeon & Bro. Basty",
      "28 Lord's Supper",
    ],
  },
  6: {
    name: "July",
    events: ["19 Prayer Vigil", "25 Dawn Prayer Breakfast"],
  },
  7: {
    name: "August",
    events: ["15 Prayer Vigil", "29 Dawn Prayer Breakfast"],
  },
  8: {
    name: "September",
    events: ["10 Prayer Vigil", "26 Dawn Prayer Breakfast"],
  },
  9: {
    name: "October",
    events: ["15 Prayer Vigil", "31 Dawn Prayer Breakfast"],
  },
  10: {
    name: "November",
    events: ["21 Thanksgiving", "28 Dawn Prayer Breakfast"],
  },
  11: {
    name: "December",
    events: [
      "1-25 Christmas Emphasis",
      "24 Christmas Eve Service",
      "25 Christmas Celebration",
      "31 New Year's Eve Service",
    ],
  },
};

export const MEMBERS_ABROAD = [
  "Gigi Kawamoto & family",
  "Marissa Libunao",
  "Mark Nagano",
  "Lito Galinato",
  "Mark Balosbalos",
  "Trecelyn Mariano & family",
  "Ferdinand Leybag & Family",
  "Jeffrel Lozano",
  "Manuel & Vilma Libunao",
  "Patricia Lebantino",
  "Dandy Ancheta & Family",
  "Uzziel Galinato",
  "Charice Natalicio",
  "Gabriel de Gamo",
  "Carmen Tomas",
  "Oscar Dela Cruz, Jr.",
  "Gadwin Buencamino",
  "Lina Damaso",
  "Ryan Manzano",
  "Brylle Danaso",
  "Rona Arce",
];

export const MISSIONARIES = [
  "Joel Marie Niepes",
  "Edward Calibayan",
  "Lomem Dela Cruz",
  "Jessie Tingson",
  "Ed Pamintuan",
  "John Ryan Jadulco",
  "Luis Yo Lane",
  "Phaltua Thiangned",
  "Joe Frank Gella",
  "Marion Dela Cruz",
  "Jonito Coronel",
  "Ron Camua",
  "Marvin J. Lebria",
  "John Mark Alisan",
  "Benoit Junior",
  "Tsegaye Wordofa",
  "Norberto Corros",
  "Phoebe Stella Giarua",
  "Harvey Paguntalon",
  "Julius Benjamin Peñas",
  "Jenny Dangpilen",
  "Harlly John Cataliño",
  "Ricky Mabazza",
  "Jiar Dela Rosa Villanueva",
  "John Tran",
  "Aguinaldo Angeles",
  "Raymond Montero",
  "Nonn Ratha",
  "Joseph De Vera",
  "Jude Pokopia",
  "Jiphthael Fortin",
  "Leo Ford Fellera",
  "Jonas Paz",
  "Gerald Magtangob",
  "Marciano Gittabao",
  "Mark Joseph Rebures",
  "Emmanuel Sibug (Peru)",
  "Braham Arizabal",
  "Fred mulenga Neymar Jr.",
  "Bob Colon",
  "Melody Ann Loro",
  "Dan Lingcoran",
  "Rodcelle Unay",
  "Januario Montenegro",
  "Richard Zimba",
  "Raymundo Zacal",
  "Pancho Galves",
  "Kevinpet Ysula",
  "Jonathan Latade",
  "Vince Louie Callos",
  "Allen Joshua Maravilla",
  "Bee Chang",
  "Rachel Ann Clavio",
  "Ervie Bendoy",
  "Adams Darko Addai",
];
